### ISSUE TITLE
Port to .Net 6

### ISSUE THREAD

**Issue by AlbertoPa** [anewtonlevey/NativeMessaging#16]
I have made a few modifications to port NativeMessaging to .Net 6 for a small project. They are here: https://github.com/AlbertoPa/NativeMessaging. If you think they are useful or want to merge them, let me know and I can make a PR.

I also plan to add a small example of extension, since the one linked in the code is not available anymore.

Thanks for your work!

**Comment by acandylevey** [comment]
Had a look through the changes, looks quite good, create the PR and I'll go over it again sometime this week
