### ISSUE TITLE
How to trigger browser click event in browser and send event to C# host app

### ISSUE THREAD

**Issue by sruthi-kurup** [anewtonlevey/NativeMessaging#2]
There are tab open, tab close, tab update events, that we can send the events to host app. Is it possible to sent the click events that we click in the browser to the c# host app?

**Comment by acandylevey** [comment]
You will need to look into what events Chrome makes available. Considering you can run Javascript in the context of the webpage however you should be able to listen to those click events. https://developer.chrome.com/extensions/content_scripts
